@chocolate=supreme caramel
@name=Marc
@taskHubName=SoSChallenge6v1

### Add chocolate
# @name chocolateAddRequest
POST http://localhost:7071/api/chocolate/{{chocolate}}

### Check status
GET http://localhost:7071/runtime/webhooks/durabletask/instances/{{chocolateAddRequest.response.body.$.id}}
    ?taskHub={{taskHubName}}
    &connection=Storage
    &code=1/yWgx52eGAyv7bADJDiFW1bpUaeslasK6gQQaO6DsC75c6suHVXJQ=="

### Remove chocolate
# @name chocolateRemoveRequest
DELETE http://localhost:7071/api/chocolate/{{chocolate}}

### Reserve chocolate
# @name reserveReponse
POST http://localhost:7071/api/reservation/{{name}}/{{chocolate}}

### Reserve chocolate
# @name unreserveReponse
DELETE http://localhost:7071/api/reservation/{{name}}


### List available & reserved chocolates
GET http://localhost:7071/api/list

